MuExporter.ct_codes = {
    -- Keys are of the form ["C, X"]
    -- At least one of C and X must be present, I think
    -- for sure X is optional
    -- Comma MUST have space after it

    ["legendary, "]                  = "legendary",
    ["akyrs_playable, "]             = "akyrs-playable",
    ["diamonds, "]                   = "diamonds",
    ["akyrs_pissandshittium, "]      = "akyrs_pissandshittium",
    ["ovn_optic, "]                  = "ovn_optics",
    -- ["paperback_temporary, "] = "",
    ["paperback_crowns, "]           = "paperbackcrowns",
    ["inactive, "]                   = "inactive",
    ["dark_edition, "]               = "darkedition",
    -- ["paperback_minor_arcana, "] = "",
    ["green, "]                      = "green",
    ["planet, "]                     = "planet",
    ["white, dark_edition"]          = "sblue-bg",
    ["spectral, "]                   = "spectral",
    ["paperback_stars, "]            = "paperbackstars",
    ["akyrs_luminous, "]             = "",
    ["clubs, "]                      = "clubs",
    ["chips, "]                      = "chips",
    -- ["black, money"] = "",
    ["tarot, "]                      = "tarot",
    ["white, akyrs_pissandshittium"] = "akyrs_pissandshittium_bg",
    ["ovn_corrupted, "]              = "ovn_corrupted",
    ["attention, "]                  = "attention",
    ["paperback_dark_suit, "]        = "paperbackdarksuits",
    ["paperback_light_suit, "]       = "paperbacklightsuits",
    ["purple, "]                     = "tarot",
    ["white, attention"]             = "orange-bg",
    ["white, money"]                 = "xcash",
    ["white, mult"]                  = "xmult",
    ["money, "]                      = "cash",
    ["mult, "]                       = "mult",
    ["white, chips"]                 = "xchips",
    ["white, red"]                   = "xmult",
    ["hearts, "]                     = "hearts",
    ["spades, "]                     = "spades",
    ["red, "]                        = "red",
    ["blue, "]                       = "blue",
}