[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Allow access to main menu, mods, and your collection in export zone
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = 'if G.STAGE == G.STAGES.RUN then'
position = "before"
payload = '''
if G.STAGE == G.STAGES.muexp_EXPORTZONE then
  main_menu = UIBox_button{ label = {localize('b_main_menu')}, button = "go_to_menu", minw = 5}
  mods = UIBox_button{ id = "mods_button", label = {localize('b_mods')}, button = "mods_button", minw = 5}
  your_collection = UIBox_button{ label = {localize('b_collection')}, button = "your_collection", minw = 5, id = 'your_collection'}
end
'''
match_indent = true

# Button to export zone
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local customize = nil"
position = "after"
payload = "local muexp_exportzone = nil"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if G.STAGE == G.STAGES.MAIN_MENU then"
position = "after"
payload = "muexp_exportzone = UIBox_button{ label = {localize('b_muexp_exportzone')}, button = 'start_export_zone', minw = 5}"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''      credits
    }})
  return t'''
position = "before"
payload = "muexp_exportzone,"
match_indent = true

# Remove cardarea size counters in export zone
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if self.ARGS.invisible_area_types[self.config.type] or"
position = "after"
payload = "(G.STAGE == G.STAGES.muexp_EXPORTZONE) or"
match_indent = true